# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/" # Location of package manifests
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
    commit-message:
      # Prefix all commit messages with "[skip ci]" to skip running tests, which will
      # fail because the Dependabot GitHub actor does not have access to secrets which
      # are necessary for running tests.
      prefix: "[skip ci]"
