name: Python package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
#        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Test and Generate Coverage Report
        run: |
           python3 -m coverage run -m pytest
           coverage xml
      - uses: actions/checkout@master
      - uses: codecov/codecov-action@v3
        with:
          files: coverage.xml
          name: codecov-umbrella
          env_vars: OS,PYTHON
          fail_ci_if_error: true
          verbose: true
