name: Unit Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
# Credit for this goes to https://til.simonwillison.net/pytest/pytest-code-coverage
      - name: Generate coverage report
        run: |
          pip install pytest-cov
          python3 -m pytest --cov=./ --cov-report=xml
      - name: Upload coverage to codecov.io
        run: bash <(curl -s https://codecov.io/bash)
        if: always()
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
